name: 2019 msbuild

on: push

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0'

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run executable
      run: |
         Write-Host "Find and execute"
         $exePath = Get-ChildItem -Path "x64\Release" -Filter "*.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
         if ($exePath) {
            Write-Host "Executable found: $exePath"
            & $exePath
         } else {
           Write-Host "No Executable found."
         }
